# GitHub Sponsors button. Add other platforms when you set them up.
# To activate the Sponsor button on the repo page, you also need to
# enroll at https://github.com/sponsors/Bigred97.
github: [Bigred97]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# custom: ["https://buymeacoffee.com/Bigred97"]
